spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    koready_backend: INFO

koready:
  kto:
    snapshot:
      storage: ${KTO_SNAPSHOT_STORAGE:s3}
