spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    koready_backend: INFO
